version: 0.2

# for info on the build phases used here:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases

# for info on the buildspec.yml syntax:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    REPO: 'webpack-base'

phases:
  install:
    commands:
      # provide access to the nodesource scoped private packages
      - npm config set @nodesource:registry http://packages-internal.nodesource.io
      - npm install

  build:
    commands:
      - npm run lint && npm run test:unit
